# Generated by Django 3.2 on 2025-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servidortenants_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(max_length=255, verbose_name='Sistema operacional')),
            ],
            options={
                'verbose_name': 'Sistema operacional',
                'verbose_name_plural': 'Sistemas operacionais',
            },
        ),
    ]
