# Generated by Django 3.2 on 2025-02-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0012_servidor_tenants'),
        ('core', '0003_operatingsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorOperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.servidor')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operatingsystem')),
            ],
            options={
                'verbose_name': 'Servidor operacional',
                'verbose_name_plural': 'Servidores operacionais',
                'unique_together': {('servidor', 'so')},
            },
        ),
    ]
