# Generated by Django 3.2 on 2025-02-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servidoroperatingsystem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidoroperatingsystem',
            options={'verbose_name': 'Servidor operacional', 'verbose_name_plural': 'Sistema operacional'},
        ),
    ]
