# Generated by Django 3.2 on 2025-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servidoroperatingsystem_options'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='predio',
            name='datacenter',
            field=models.CharField(choices=[(1, 'SESUP'), (2, 'COIDS')], default=1, max_length=5),
        ),
    ]
