# Generated by Django 3.2 on 2025-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250407_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='datacenter',
            field=models.CharField(max_length=255, null=True, verbose_name='DataCenter'),
        ),
    ]
