# Generated by Django 3.2 on 2025-04-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_predio_datacenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='datacenter',
        ),
    ]
