# Generated by Django 3.2 on 2025-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servidoroperatingsystem'),
        ('infra', '0012_servidor_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='tenants',
            field=models.ManyToManyField(blank=True, null=True, to='core.OperatingSystem'),
        ),
    ]
