# Generated by Django 3.2 on 2025-04-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250407_1649'),
        ('infra', '0014_auto_20250206_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='datacenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_predio', to='core.predio', verbose_name='Datacenter'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_datacenter', to='core.predio', verbose_name='Prédio'),
        ),
    ]
