# Generated by Django 3.2 on 2025-04-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_predio_datacenter'),
        ('infra', '0015_auto_20250410_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='datacenter',
            field=models.ForeignKey(choices=[(1, 'SESUP'), (2, 'COIDS')], default=1, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos_predio', to='core.predio', verbose_name='Datacenter'),
        ),
    ]
