# Generated by Django 3.2 on 2025-04-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0016_alter_equipamento_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='datacenter',
            field=models.IntegerField(blank=True, choices=[(1, 'SESUP'), (2, 'COIDS')], null=True, verbose_name='Datacenter'),
        ),
    ]
