# Generated by Django 3.2 on 2025-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0017_alter_equipamento_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='datacenter',
            field=models.CharField(blank=True, choices=[('SESUP', 'SESUP'), ('COIDS', 'COIDS')], max_length=255, null=True, verbose_name='Datacenter'),
        ),
    ]
