# Generated by Django 3.2 on 2025-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_predio_datacenter'),
        ('infra', '0018_alter_equipamento_datacenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientevirtual',
            name='network',
            field=models.PositiveSmallIntegerField(choices=[(1, 'INTERNA'), (2, 'DMZ')], default=1, verbose_name='Tipo de Rede'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='so',
            field=models.ManyToManyField(blank=True, to='core.OperatingSystem'),
        ),
    ]
